# SOPS configuration for secrets management
# This file defines which keys can decrypt which secrets

# To generate age key:
# age-keygen -o ~/.config/sops/age/keys.txt

# To convert SSH key to age:
# ssh-to-age < ~/.ssh/id_ed25519.pub

keys:
  # Add your age public key here after generating
  # - &user_semyenov age1...
  
  # System host key (generate with ssh-keygen -t ed25519 -f /etc/ssh/ssh_host_ed25519_key)
  # - &host_nixos age1...

creation_rules:
  # Default rule for all secrets
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
          # - *user_semyenov
          # - *host_nixos
          
  # User-specific secrets
  - path_regex: secrets/users/[^/]+\.yaml$
    key_groups:
      - age:
          # - *user_semyenov